### ISSUE TITLE
6.6.4 TODO list

### ISSUE THREAD

**Issue by Su5eD** [Su5eD/MinecraftForge#4]
- [X] Replace LaunchWrapper with a less hacky, simple main class
- [X] Fix Skins
- [X] Install-Time Binpatching (possibly makes runtime deobf easier) 
- [x] Fix [NPE in options.txt](https://bugs.mojang.com/browse/MCL-5837)
- [x] Fix `Clean` dev project run args
- [x] Modernize MDK Gradle practices
- [x] Update to ForgeGradle 5
- [x] README
